import { View, Text, ScrollView, TouchableOpacity, StyleSheet } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { Colors, Fonts, Spacing, Radius } from '@constants/theme';

const EFFECTIVE_DATE = 'April 13, 2026';

export default function PrivacyPolicyScreen() {
  return (
    <SafeAreaView style={styles.container}>
      <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>
        <View style={styles.header}>
          <TouchableOpacity onPress={() => router.back()}>
            <Text style={styles.backText}>← Back</Text>
          </TouchableOpacity>
          <Text style={styles.title}>Privacy Policy</Text>
          <Text style={styles.effectiveDate}>Effective: {EFFECTIVE_DATE}</Text>
        </View>

        <Section title="Overview">
          Naksha ("the App") is a Vedic astrology and self-inquiry application developed by Naksha
          ("we", "us", or "our"). Your privacy is important to us. This Privacy Policy explains what
          information we collect, how we use it, and your choices regarding your data.
        </Section>

        <Section title="1. Information We Collect">
          <Bold>a) Information You Provide</Bold>
          {'\n'}- Full name (as entered during onboarding)
          {'\n'}- Date of birth
          {'\n'}- Time of birth
          {'\n'}- Place of birth (city, state, country)
          {'\n'}- Partner details entered for compatibility readings (name, date of birth, time, place)
          {'\n'}- Full name at birth (for numerology readings)
          {'\n'}- Questions and messages sent to the AI Guru
          {'\n\n'}<Bold>b) Information Generated by the App</Bold>
          {'\n'}- Geographic coordinates (latitude/longitude) derived from your place of birth via geocoding
          {'\n'}- Timezone derived from your location
          {'\n'}- Vedic birth chart data (Lagna, planetary positions, Nakshatras, Dasha periods, Yogas)
          {'\n'}- Navamsha (divisional) chart data
          {'\n'}- Numerology calculations (Life Path, Destiny, Soul Urge, Personality, Birthday numbers)
          {'\n'}- Chinese astrology profile (zodiac animal, element, year pillar)
          {'\n'}- AI-generated readings and analysis
          {'\n\n'}<Bold>c) Images</Bold>
          {'\n'}- Palm photographs taken or selected for palmistry analysis are processed temporarily and
          are not stored on our servers after analysis is complete.
          {'\n\n'}<Bold>d) Subscription Information</Bold>
          {'\n'}- Subscription status and type (monthly, annual, or lifetime) are managed by Apple App
          Store and Google Play Store through RevenueCat. We do not directly collect or store your
          payment information.
        </Section>

        <Section title="2. How We Use Your Information">
          We use your information solely to provide the App's features:
          {'\n\n'}- Generate your Vedic birth chart and planetary positions via the Prokerala Astrology API
          {'\n'}- Provide personalized AI readings (daily, palm, numerology, Chinese astrology, Lal Kitab,
          compatibility) via the Anthropic Claude API
          {'\n'}- Personalize the AI Guru's responses based on your chart profile
          {'\n'}- Geocode your place of birth to coordinates using the OpenStreetMap Nominatim service
          {'\n'}- Manage your subscription entitlements via RevenueCat
          {'\n'}- Save your readings locally on your device for future reference
          {'\n\n'}We do not use your data for advertising, profiling, marketing, or any purpose beyond
          delivering the App's features.
        </Section>

        <Section title="3. Data Storage">
          <Bold>Local Storage</Bold>
          {'\n'}Your birth data, chart data, saved readings (up to 50), Guru conversation history (up to
          50 messages), saved charts, and preferences are stored locally on your device using
          AsyncStorage. This data never leaves your device except when sent to the third-party services
          described in Section 4.
          {'\n\n'}<Bold>No Account or Cloud Sync</Bold>
          {'\n'}Naksha does not require an account. We do not maintain user accounts, databases, or cloud
          storage of your personal data. If you delete the App, all locally stored data is permanently
          removed.
        </Section>

        <Section title="4. Third-Party Services">
          The App communicates with the following third-party services to provide its features:
          {'\n\n'}<Bold>a) Anthropic (Claude API)</Bold>
          {'\n'}Your birth data, chart data, and questions are sent to Anthropic's Claude API to generate
          AI-powered readings. Palm images are sent as base64-encoded data for analysis. When you use the
          Compatibility feature, the birth details you enter for your partner are also transmitted to
          Anthropic as part of the compatibility analysis. Anthropic's privacy policy governs their
          handling of this data.
          {'\n\n'}<Bold>b) Prokerala Astrology API</Bold>
          {'\n'}Your birth date, time, and coordinates are sent to Prokerala to calculate your Vedic birth
          chart, planetary positions, Dasha periods, and Yogas.
          {'\n\n'}<Bold>c) OpenStreetMap Nominatim</Bold>
          {'\n'}Your place of birth text is sent to OpenStreetMap's Nominatim geocoding service to obtain
          geographic coordinates. No personal identifiers are included in this request.
          {'\n\n'}<Bold>d) RevenueCat</Bold>
          {'\n'}RevenueCat manages subscription verification and purchase restoration. RevenueCat receives
          a device identifier and subscription transaction data from the App Store or Play Store. We do
          not send your birth data or personal information to RevenueCat.
          {'\n\n'}<Bold>e) Apple App Store / Google Play Store</Bold>
          {'\n'}Subscription purchases are processed entirely by Apple or Google. We do not have access to
          your payment method, billing address, or financial information.
        </Section>

        <Section title="5. Data Sharing">
          We do not sell, rent, trade, or share your personal data with any third party for marketing,
          advertising, or data brokerage purposes.
          {'\n\n'}Data is shared only with the third-party services listed in Section 4, solely for the
          purpose of delivering the App's features. Each service receives only the minimum data
          required for its function.
        </Section>

        <Section title="6. Data Retention">
          - All personal data is stored locally on your device and persists until you reset your
          profile or delete the App.
          {'\n'}- Palm images are processed in memory during analysis and are not persisted after the
          reading is generated.
          {'\n'}- Guru conversation history is limited to the most recent 50 messages.
          {'\n'}- Saved readings are limited to the most recent 50 entries.
          {'\n'}- We do not retain any data on our servers.
        </Section>

        <Section title="7. Your Rights & Choices">
          <Bold>Reset Your Data</Bold>
          {'\n'}You can reset all personal data at any time from the Profile screen by tapping "Reset
          Profile". This permanently deletes all birth data, chart data, saved readings, and
          conversation history from your device.
          {'\n\n'}<Bold>Delete the App</Bold>
          {'\n'}Uninstalling the App removes all locally stored data. Since we do not store data on
          external servers, deletion is complete and irreversible.
          {'\n\n'}<Bold>Camera & Photo Access</Bold>
          {'\n'}Camera and photo library access is requested only when you use the palm reading feature.
          You can revoke these permissions at any time through your device settings.
        </Section>

        <Section title="8. Children's Privacy">
          Naksha is not directed at children under the age of 13. We do not knowingly collect personal
          information from children. If you believe a child has provided us with personal information,
          please contact us so we can take appropriate action.
        </Section>

        <Section title="9. Security">
          Your data is stored locally on your device and protected by your device's built-in security
          mechanisms (passcode, biometrics, encryption). API communications are conducted over HTTPS.
          We do not store API keys on your device in plaintext — they are injected at build time
          through secure environment variables.
        </Section>

        <Section title="10. Changes to This Policy">
          We may update this Privacy Policy from time to time. Changes will be reflected in the App
          with an updated effective date. Continued use of the App after changes constitutes acceptance
          of the revised policy.
        </Section>

        <Section title="11. Disclaimer">
          Naksha is designed for spiritual self-inquiry, personal reflection, and entertainment only.
          Readings and guidance provided by the App are not medical, legal, financial, or professional
          advice. Always consult qualified professionals for important life decisions.
        </Section>

        <Section title="12. Contact Us">
          If you have questions about this Privacy Policy or your data, please contact us at:
          {'\n\n'}Email: nakshaguide@gmail.com
        </Section>

        <View style={{ height: 100 }} />
      </ScrollView>
    </SafeAreaView>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <View style={styles.section}>
      <Text style={styles.sectionTitle}>{title}</Text>
      <Text style={styles.sectionBody}>{children}</Text>
    </View>
  );
}

function Bold({ children }: { children: React.ReactNode }) {
  return <Text style={styles.bold}>{children}</Text>;
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.midnight },
  content: { paddingBottom: 40 },
  header: { padding: Spacing.md },
  backText: { fontSize: 14, color: Colors.gold, fontFamily: Fonts.cinzel, marginBottom: 8 },
  title: { fontSize: 24, fontFamily: Fonts.cinzel, color: Colors.gold },
  effectiveDate: { fontSize: 12, color: Colors.muted, fontFamily: Fonts.cormorantItalic, marginTop: 4 },
  section: { paddingHorizontal: Spacing.md, marginBottom: Spacing.lg },
  sectionTitle: { fontSize: 14, fontFamily: Fonts.cinzel, color: Colors.gold, marginBottom: 8 },
  sectionBody: { fontSize: 14, color: Colors.star, fontFamily: Fonts.crimson, lineHeight: 22, opacity: 0.85 },
  bold: { fontFamily: Fonts.cinzel, fontSize: 12, color: Colors.star },
});
