import { View, Text, ScrollView, TouchableOpacity, StyleSheet } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { Colors, Fonts, Spacing, Radius } from '@constants/theme';

const EFFECTIVE_DATE = 'April 13, 2026';

export default function TermsOfServiceScreen() {
  return (
    <SafeAreaView style={styles.container}>
      <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>
        <View style={styles.header}>
          <TouchableOpacity onPress={() => router.back()}>
            <Text style={styles.backText}>← Back</Text>
          </TouchableOpacity>
          <Text style={styles.title}>Terms of Service</Text>
          <Text style={styles.effectiveDate}>Effective: {EFFECTIVE_DATE}</Text>
        </View>

        <Section title="Overview">
          These Terms of Service ("Terms") govern your use of the Naksha application ("the App")
          developed by Naksha ("we", "us", or "our"). By downloading, installing, or using the App,
          you agree to be bound by these Terms. If you do not agree, please do not use the App.
        </Section>

        <Section title="1. Description of Service">
          Naksha is a Vedic astrology and self-inquiry application that provides:
          {'\n\n'}- Vedic birth chart generation and analysis
          {'\n'}- AI-powered personalized readings (daily, palm, numerology, Chinese astrology, Lal Kitab,
          compatibility)
          {'\n'}- An AI Guru for spiritual guidance conversations
          {'\n'}- Numerology calculations and interpretations
          {'\n'}- Chinese astrology (BaZi Four Pillars) analysis
          {'\n'}- Lal Kitab planetary remedies
          {'\n'}- Palm reading analysis via photograph
          {'\n'}- Vedic compatibility (Ashtakoota) analysis
        </Section>

        <Section title="2. Disclaimer — For Entertainment & Self-Inquiry Only">
          THE APP IS PROVIDED STRICTLY FOR SPIRITUAL SELF-INQUIRY, PERSONAL REFLECTION, AND
          ENTERTAINMENT PURPOSES.
          {'\n\n'}The readings, predictions, guidance, remedies, and analysis provided by the App —
          whether generated by AI or calculated from astrological data — do NOT constitute:
          {'\n\n'}- Medical or health advice
          {'\n'}- Legal advice
          {'\n'}- Financial or investment advice
          {'\n'}- Psychological or mental health counseling
          {'\n'}- Professional advice of any kind
          {'\n\n'}You should always consult qualified professionals for decisions regarding your health,
          finances, legal matters, and other important life circumstances. We are not responsible for
          any actions you take based on the App's content.
        </Section>

        <Section title="3. Eligibility">
          You must be at least 13 years of age to use the App. By using the App, you represent that
          you meet this age requirement. If you are between 13 and 18, you represent that a parent or
          legal guardian has reviewed and agreed to these Terms on your behalf.
        </Section>

        <Section title="4. User Conduct">
          You agree not to:
          {'\n\n'}- Use the App for any unlawful purpose
          {'\n'}- Attempt to reverse-engineer, decompile, or extract source code from the App
          {'\n'}- Interfere with or disrupt the App's services or servers
          {'\n'}- Use automated systems or bots to access the App
          {'\n'}- Misrepresent your identity or provide false information
          {'\n'}- Use the App's AI features to generate harmful, abusive, or misleading content
          {'\n'}- Redistribute, resell, or commercially exploit the App's content or readings
        </Section>

        <Section title="5. Premium Subscription">
          <Bold>a) Plans & Pricing</Bold>
          {'\n'}Naksha offers premium subscriptions through the Apple App Store and Google Play Store:
          {'\n'}- Monthly: $9.99/month
          {'\n'}- Annual: $59.99/year
          {'\n'}- Lifetime: $149.99 one-time purchase
          {'\n\n'}<Bold>b) Auto-Renewal</Bold>
          {'\n'}Monthly and annual subscriptions auto-renew at the end of each billing period unless
          cancelled at least 24 hours before the renewal date. Lifetime purchases do not renew.
          {'\n\n'}<Bold>c) Cancellation</Bold>
          {'\n'}You can cancel your subscription at any time through your Apple App Store or Google Play
          Store account settings. Cancellation takes effect at the end of the current billing period.
          You will retain access to premium features until your subscription expires.
          {'\n\n'}<Bold>d) Refunds</Bold>
          {'\n'}Refund requests are handled by Apple or Google in accordance with their respective refund
          policies. We do not process refunds directly.
          {'\n\n'}<Bold>e) Free Tier</Bold>
          {'\n'}Non-premium users have access to limited features including up to 3 AI Guru conversations
          per day and basic chart information. Premium features include unlimited conversations, palm
          reading, numerology, Chinese astrology, Lal Kitab remedies, compatibility analysis, and
          advanced chart features.
        </Section>

        <Section title="6. Intellectual Property">
          All content, design, graphics, trademarks, and intellectual property within the App are owned
          by Naksha or its licensors. AI-generated readings are produced using third-party AI models
          and are provided to you for personal, non-commercial use only.
          {'\n\n'}You may not reproduce, distribute, modify, or create derivative works from the App's
          content without our prior written consent.
        </Section>

        <Section title="7. AI-Generated Content">
          Readings and guidance are generated by artificial intelligence (Anthropic Claude). While we
          strive for accuracy and helpfulness:
          {'\n\n'}- AI-generated content may contain inaccuracies or generalizations
          {'\n'}- Readings are not deterministic — the same input may produce different outputs
          {'\n'}- The AI does not have consciousness, intuition, or psychic abilities
          {'\n'}- Content should be treated as reflective prompts, not factual predictions
          {'\n'}- We do not guarantee the accuracy, completeness, or reliability of any reading
        </Section>

        <Section title="8. Third-Party Services">
          The App relies on third-party services (Anthropic, Prokerala, OpenStreetMap, RevenueCat,
          Apple, Google) to function. We are not responsible for outages, errors, or changes to these
          services. Service interruptions may temporarily affect the App's features.
        </Section>

        <Section title="9. Limitation of Liability">
          TO THE MAXIMUM EXTENT PERMITTED BY LAW, NAKSHA AND ITS DEVELOPERS SHALL NOT BE LIABLE FOR
          ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE
          OF THE APP, INCLUDING BUT NOT LIMITED TO:
          {'\n\n'}- Decisions made based on the App's readings or guidance
          {'\n'}- Loss of data due to device failure or App deletion
          {'\n'}- Service interruptions or API outages
          {'\n'}- Inaccuracies in astrological calculations or AI-generated content
          {'\n\n'}Our total liability for any claim arising from the App shall not exceed the amount you
          paid for the App in the 12 months preceding the claim, or $50, whichever is greater.
        </Section>

        <Section title="10. Indemnification">
          You agree to indemnify and hold harmless Naksha and its developers from any claims, damages,
          or expenses arising from your use of the App, violation of these Terms, or infringement of
          any third-party rights.
        </Section>

        <Section title="11. Termination">
          We reserve the right to suspend or terminate your access to the App at any time for
          violation of these Terms. You may stop using the App at any time by uninstalling it.
        </Section>

        <Section title="12. Changes to These Terms">
          We may modify these Terms at any time. Updated Terms will be reflected in the App with a
          revised effective date. Continued use after changes constitutes acceptance of the updated
          Terms.
        </Section>

        <Section title="13. Governing Law">
          These Terms shall be governed by and construed in accordance with the laws of the
          jurisdiction in which Naksha operates, without regard to conflict of law principles.
        </Section>

        <Section title="14. Contact Us">
          If you have questions about these Terms, please contact us at:
          {'\n\n'}Email: support@nakshatra.app
        </Section>

        <View style={{ height: 100 }} />
      </ScrollView>
    </SafeAreaView>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <View style={styles.section}>
      <Text style={styles.sectionTitle}>{title}</Text>
      <Text style={styles.sectionBody}>{children}</Text>
    </View>
  );
}

function Bold({ children }: { children: React.ReactNode }) {
  return <Text style={styles.bold}>{children}</Text>;
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.midnight },
  content: { paddingBottom: 40 },
  header: { padding: Spacing.md },
  backText: { fontSize: 14, color: Colors.gold, fontFamily: Fonts.cinzel, marginBottom: 8 },
  title: { fontSize: 24, fontFamily: Fonts.cinzel, color: Colors.gold },
  effectiveDate: { fontSize: 12, color: Colors.muted, fontFamily: Fonts.cormorantItalic, marginTop: 4 },
  section: { paddingHorizontal: Spacing.md, marginBottom: Spacing.lg },
  sectionTitle: { fontSize: 14, fontFamily: Fonts.cinzel, color: Colors.gold, marginBottom: 8 },
  sectionBody: { fontSize: 14, color: Colors.star, fontFamily: Fonts.crimson, lineHeight: 22, opacity: 0.85 },
  bold: { fontFamily: Fonts.cinzel, fontSize: 12, color: Colors.star },
});
